aws_region         = "us-east-1"
access_key         = "ACCESS KEY"
secret_key         = "SECRET KEY"
aws_vpc_cidr_block = "10.0.0.0/16"
aws_az             = "us-east-1a"
instance_ami       = "ami-04505e74c0741db8d"
instance_type      = "t2.micro"